export default function Head() {
  return (
    <>import FontFamily from '@fontshare/font-family'npm install fontshare-font-family-namenpm install fontshare-font-family-name
      <title>IMDB clone</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://api.fontshare.com/v2/css?f[]=satoshi@700,300,400&display=swap" rel="stylesheet"></link>
    </>
  )
}
